### PR TITLE
created Product model

### LINKED ISSUE #6: Product Model
## Feature Description
1. int ProductId [pk]
2. string Name [Required]
3. string(255) Description [Required]
4. double Price [Required]
5. int ProductTypeId [fk] 
6. ProductType productType
7. ICollection LineItem (to establish foreign key relationship)
8. date added

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 
1. Touched Product.cs model
2. Added columns to table.
## Steps to test
1. switch to branch productModel
2. look in Models folder
3. open Product.cs
4. double check to make sure all properties listed in the issue ticked are implemented correctly.
## Link to Feature Ticket

Provide the issue number that this pull request fixes
#6

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
Should the local variable "productType" on line 24 be replaced with "ProductType" to follow upper camelcase naming convention of properties?

Also BangazonWeb.xproj should be removed.

**Review by HubDub — DISMISSED** [review]
I agree with Grant on the ProductType on line 24. also, if we use "DateAdded" for the DateTime we need to remember to change this on our ERD which says "DateCreated"

**Review by Jgregnier — APPROVED** [review]
Looks good to me

**Comment by JamsDuke** [comment]
Made ProductTypeId required

**Pull request merged**
