### PR TITLE
Ddw shopping cart total

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Include the applicable information from the list below here 

1. Added logic in ShoppingCart method to add a CartTotal to the shopping cart view

## Steps to Test

Include the applicable information from the list below here

1. Cannot test until merged with ShoppingCartView

## Link to Feature Ticket

 #142

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
Pulled code, works as intended.

**Review by thrashMoneyVillainare — COMMENTED** [review]
it works~

**Comment by HubDub** [comment]
looks good to me

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by thrashMoneyVillainare — APPROVED** [review]

**Pull request merged**
