### PR TITLE
Added CustomerForm to BaseViewModel

### PR DESCRIPTION
**Pull request by csmalley89**
## Pull Request Description

Changed asp-action, asp-for, and @ model syntax to correct format.
## Steps to test
1. Look for spelling errors.
2. Comment any changes that may be incorrect.
## Link to Feature Ticket
#43

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
Looks Good To Me

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by thrashMoneyVillainare — COMMENTED** [review]
I can get behind this.

**Review by JamsDuke — COMMENTED** [review]
looks solid

**Review by HubDub — APPROVED** [review]
ok

**Pull request merged**
