### PR TITLE
Product Form Validation

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Include the applicable information from the list below here 
1. I added product validation to the add new product form
## Steps to Test

Include the applicable information from the list below here
1. Switch to the branch `ddw-validation`
2. Go to the New Product form
3. Try to submit the form and break it
4. Examples include, added characters other than numbers to the price, submitting without adding everything
5. If you can't break it then it's good! 
## Link to Feature Ticket
#121

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
LGTM

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by JamsDuke — COMMENTED** [review]
Code has been pulled, tested, and Jamie approved!

**Review by thrashMoneyVillainare — COMMENTED** [review]
lgtm

**Review by HubDub — APPROVED** [review]
tested and working on my computer

**Pull request merged**
