### PR TITLE
Jzr shopping cart view4real

### PR DESCRIPTION
**Pull request by thrashMoneyVillainare**
## Pull Request Description

1. ShoppingCart View is now wired up with the customers products, an "Add Payment" button, and a "Select Payment Type" drop down list.

## Steps to Test
1. go to Terminal
1. git fetch
1. git checkout jzr-ShoppingCartView4Real
1. select customer
1. add products
1. go to shopping cart view
1. click products links to go to single/detail view 
1. click Add Payment button

## Link to Feature Ticket

#44 

Provide the issue number that this pull request fixes
Example: #1

### CODE REVIEW

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by JamsDuke — COMMENTED** [review]
Pulled and tested, LGTM

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by JamsDuke — APPROVED** [review]
LGTM

**Pull request merged**
