### PR TITLE
Ddw submit product

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Include the applicable information from the list below here 

Fixed DBInitializer file so that the database seeds correctly
Got form to submit data to the database and to the products page
## Steps to Test

Include the applicable information from the list below here
1. Switch to branch `ddw-submit-products`
2. Run `dotnet ef database update`
3. Make sure there are no errors in the code or on run 
## Link to Feature Ticket
#47 #97

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
Code pulled, works.  Looks good to merge.

**Review by Jgregnier — COMMENTED** [review]
LGTM

**Comment by HubDub** [comment]
After navigating into this branch I was able to recreate the database - it populated with seed data, run, and then successfully navigate through working areas of the site. Good to go.

**Review by thrashMoneyVillainare — COMMENTED** [review]
I am corroborating Grant and Deb's approval.

**Review by Jgregnier — APPROVED** [review]

**Review by csmalley89 — COMMENTED** [review]
👍

**Pull request merged**
