### PR TITLE
Removed Create Account from NavBar

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

Removed Create Account Option from NavBar

## Steps to Test

1. Check that Create Account Option is no longer there in the NavBar.

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
Code has been pulled and tested, LGTM

**Review by csmalley89 — COMMENTED** [review]
👍

**Comment by HubDub** [comment]
looks good

**Review by delaineackerman — COMMENTED** [review]
lgtm

**Review by thrashMoneyVillainare — APPROVED** [review]
lgtm

**Pull request merged**
