### PR TITLE
replaced ERD file with updated ERD

### PR DESCRIPTION
**Pull request by HubDub**
## Pull Request Description

Include the applicable information from the list below here 

updated updated ERD png file to replace out of date one. 

## Steps to Test

examine ERD for accuracy

## Link to Feature Ticket

#149

### CODE REVIEW

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by thrashMoneyVillainare — COMMENTED** [review]
jollyGood

**Review by JamsDuke — COMMENTED** [review]
LGTM

**Review by Jgregnier — COMMENTED** [review]
LGTM

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
