### PR TITLE
modified TypesList method in ProductsController to load sub types for…

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 

1.  Modified TypesList method to load subtypes in the view.
2.  Wrote view to display Sub Types in TypesList.cshtml

## Steps to Test

Include the applicable information from the list below here

1. Switch to branch jd-subTypeListView
1. Make sure that sub type categories load when you click on a given type.

## Link to Feature Ticket

Provide the issue number that this pull request fixes
Example: #41

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
LGTM Jamie

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by thrashMoneyVillainare — COMMENTED** [review]
lgtm

**Comment by HubDub** [comment]
it does load subcategories from this view. good to go.

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
