### PR TITLE
added hr tag to top of repeated element

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 
1. Hotfix.  Added hr tag to top of repeated element.
## Steps to Test

Include the applicable information from the list below here
1. With data from database, elements should display below the nav bar.
## Link to Feature Ticket
#100

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
LGTM

**Review by thrashMoneyVillainare — COMMENTED** [review]
okieDokie

**Review by HubDub — COMMENTED** [review]
looks good

**Review by csmalley89 — COMMENTED** [review]
🇺🇸 👍

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
