### PR TITLE
Subproducts description

### PR DESCRIPTION
**Pull request by csmalley89**
## Pull Request Description

Shows a description of every subproduct type above the list of products that fit into that subproduct type.

## Steps to Test

1. git checkout subproduct
1. Navigate to a product type, then click on a subproduct type to see its description

## Link to Feature Ticket

#162

### CODE REVIEW

**Review by csmalley89 — COMMENTED** [review]
🤑

**Comment by HubDub** [comment]
this works for me. the description does show up in the subcategory.

**Review by JamsDuke — COMMENTED** [review]
code works.  A little concerned that it has changes from another branch on it.  Though those shouldnt bother anything as they are already on the master branch.

**Review by Jgregnier — COMMENTED** [review]
🍊

**Review by delaineackerman — COMMENTED** [review]
lgtm

**Review by thrashMoneyVillainare — APPROVED** [review]
👌

**Pull request merged**
