### PR TITLE
Jzr payment view

### PR DESCRIPTION
**Pull request by thrashMoneyVillainare**
## Pull Request Description

Added 'add-PaymentType' functionality.

# NOTE: line 114 in CustomersController => the local variable must be the same name as its type.

## Steps to Test

1. switch to jzr-PaymentView
1. select customer
1. add item
1. go to shoppingCart
1. add PaymentType
1. submit PaymentType
1. you will be redirected to the shoppingCart
1. payment type will be added in the drop down list

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
pulled, tested, lgtm

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by Jgregnier — COMMENTED** [review]
🍊

**Comment by HubDub** [comment]
on this branch I am able to create a new payment type. looks good to me.

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by Jgregnier — APPROVED** [review]

**Pull request merged**
