### PR TITLE
Gr hotfixes

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

Hotfixed the problems we worked through together.
New customer functionality implemented 
## Steps to Test

Check for errors

### CODE REVIEW

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by thrashMoneyVillainare — COMMENTED** [review]
looks good 🇺🇸

**Review by csmalley89 — COMMENTED** [review]
👍

**Comment by HubDub** [comment]
looks good

**Review by JamsDuke — APPROVED** [review]
groovy

**Pull request merged**
