### PR TITLE
Added dynamic routing to the link in the navbar

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Modified the BaseView Model and the Menu Partial to change the routing based on whether or not there is an active customer. 

## Steps to Test

Include the applicable information from the list below here

1. git fetch
1. checkout `ddw-routing`
1. Make sure that when a customer has not been selected the route goes to Customers/New and pulls up the form
1. Make that when a customer has been selected the route goes to Customers/ShoppingCart

## Link to Feature Ticket

 #130

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
LGTM

**Review by JamsDuke — COMMENTED** [review]
Pulled and tested, LGTM

**Comment by HubDub** [comment]
it does navigate to shopping cart view now

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by thrashMoneyVillainare — APPROVED** [review]
🍇

**Pull request merged**
