### PR TITLE
Added SubProductTypes as a table in the database

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Include the applicable information from the list below here 

Migrations needed to be deleted because the database has a new table.
The new table is called SubProductType
The seeded data needed to be changed to include sub product types
The ProductType model needed to be changed to the have a collection of subproducttypes rather than products
## Steps to Test

Include the applicable information from the list below here
1. Switch to new branch `ddw-subproducts-model`
2. run `dotnet ef database update`
3. Make sure the database is updated with the seeded data
## Link to Feature Ticket
#86

### CODE REVIEW

**Comment by HubDub** [comment]
my database updated correctly with the subproduct types. good to go.

**Review by JamsDuke — APPROVED** [review]
tested your code.  Database updates are showing.

**Review by csmalley89 — COMMENTED** [review]
The code is solid, however the actual names of product types and subtypes is ambiguous. I recommend making the following changes. 
ProductType ==> SubProductType
Electronics ==> Portable Audio Devices
Food and Drink ==> Flavored Water
Appliances ==> Refridgerators

**Review by Jgregnier — COMMENTED** [review]
OK

**Pull request merged**
