### PR TITLE
Submit Order Button

### PR DESCRIPTION
**Pull request by csmalley89**
## Pull Request Description

Submit order button routes users to order completed page. Upon pressing the button it patches the order to the database.

## Steps to Test

1. Check out orderCompleted branch.
1. Nuke your migrations and database file.
1. Export DB path.
1. Add migrations.
1. Update DB.
1. dotnet run
1. Comment any issues.

## Link to Feature Ticket

#155

### CODE REVIEW

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by Jgregnier — COMMENTED** [review]
🍊

**Review by JamsDuke — COMMENTED** [review]
Fix the git bug and youre good to go!

**Comment by HubDub** [comment]
good to go! git!

**Review by thrashMoneyVillainare — COMMENTED** [review]
git it!

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
