### PR TITLE
Added hide and show to AddToCart button and sell a product link. Adde…

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

1. Changed button from "Create a product" to "Sell a product"
1. Customer cannot access sell a product or add a product to cart if they are not logged in.

## Steps to Test

1. git fetch
1. git checkout gr-SellAProductButton 
1. run the program
1. Make sure you aren't able to add to cart or sell a product unless you are logged in.

## Link to Feature Ticket

#160 
#159 
#158

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
Code pulled, tested, works as intended.  LGTM

**Review by csmalley89 — COMMENTED** [review]
👍

**Comment by HubDub** [comment]
looks good to me

**Review by thrashMoneyVillainare — COMMENTED** [review]
vGood

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
