### PR TITLE
Jd single type product list

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 

1. Completed ProductsInSubTypeView
1. Added hotfix to Single view to remove extra dollar sign

## Steps to Test

Include the applicable information from the list below here

1. Switch to branch jd-singleTypeProductList
1. Add a new product, and verify that it shows up in the appropriate sub category, or look for an existing product.

## Link to Feature Ticket

Provide the issue number that this pull request fixes
Example: #109

### CODE REVIEW

**Review by csmalley89 — COMMENTED** [review]
👍

**Comment by HubDub** [comment]
I was able to navigate to a single product. good to go.

**Review by thrashMoneyVillainare — COMMENTED** [review]
looks good

**Review by delaineackerman — COMMENTED** [review]
Was able to navigate and see sub-types.

**Review by Jgregnier — APPROVED** [review]
Good

**Pull request merged**
