### PR TITLE
Shopping Cart View Model

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

Created the ShoppingCartViewModel.cs in the ViewModels folder.
The ShoppingCartViewModel should pass the view a list of products(all products on active order),
and a list of PaymentTypes (All PaymentTypes of the active user)
## Steps to Test

Check that an IEnumerable of type products is being passed
Check that an IEnumerable of type PaymentTypes is being passed
## Link to Feature Ticket
#77

### CODE REVIEW

**Review by csmalley89 — APPROVED** [review]
👍

**Review by delaineackerman — COMMENTED** [review]
I think you're going to need to create a SelectListItem List for the Payment Types - similar to how the Customer Drop Down was created on the BaseViewModel

**Review by JamsDuke — COMMENTED** [review]
Looks good to me!

**Comment by HubDub** [comment]
looks good after the changes.

**Review by thrashMoneyVillainare — APPROVED** [review]
Grape!

**Review by delaineackerman — COMMENTED** [review]
LGTM - well thought out!

**Review by JamsDuke — CHANGES_REQUESTED** [review]
Code looks good, but should it have the migrations with it?

**Review by JamsDuke — APPROVED** [review]

**Pull request merged**
