### PR TITLE
removed redundant heading for Join Bangazon

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 

1. Removed extra "Join Bangazon" heading on New Customer page.

## Steps to Test

Include the applicable information from the list below here

1. Go to New Customer
1. Verify that heading is not redundant and only appears once.

## Link to Feature Ticket

Provide the issue number that this pull request fixes
Example: #144

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
LGTM

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by delaineackerman — COMMENTED** [review]
lgtm

**Comment by HubDub** [comment]
looks good

**Review by thrashMoneyVillainare — APPROVED** [review]
okie dokie

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
