### PR TITLE
Single.cshtml File

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Include the applicable information from the list below here 
1. Added Razor templating to the Single.cshtml file to show a product's details
## Steps to Test

Include the applicable information from the list below here
1. Switch to the ddw-single-view branch to test code
2. View changes and look for any errors
## Link to Feature Ticket
#42

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
👍

**Review by thrashMoneyVillainare — COMMENTED** [review]
okie dokie

**Comment by HubDub** [comment]
looks good to me

**Review by JamsDuke — APPROVED** [review]
Looks good!

**Review by csmalley89 — APPROVED** [review]
LGTM

**Review by Jgregnier — APPROVED** [review]

**Pull request merged**
