### PR TITLE
Ddw shopping cart items

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Include the applicable information from the list below here 

1. Added a property of ShoppingCartItems to the BaseViewModel.
1. Added the ShoppingCartItems to the Navbar

## Steps to Test

Include the applicable information from the list below here

1. get fetch
1. switch to `ddw-shoppingCart-items`
1. make sure that nothing is showing up when a customer isn't chosen and that 0 is showing up when a customer is selected. 
1. Make sure the logic in the BaseViewModel looks correct. 

## Link to Feature Ticket

#129

### CODE REVIEW

**Review by thrashMoneyVillainare — APPROVED** [review]
lgtu

**Review by JamsDuke — COMMENTED** [review]
lgtm

**Review by csmalley89 — COMMENTED** [review]
👍

**Comment by HubDub** [comment]
looks good

**Pull request merged**
