### PR TITLE
Implemented 'CustomerName' on the SingleProductViewModel, contingent on Zack's PR

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

1. When viewing a single product, the Customer's name should be displayed below the description but before the price.
1. It currently doesn't work because we haven't resolved the issue of form validation with the payment type pr, which also has our new products model.

## Steps to Test

1. This will not work until we have the customerId on the product model.
1. Check for logical errors and for spelling mistakes.

### CODE REVIEW

**Review by thrashMoneyVillainare — COMMENTED** [review]
lookin good

**Comment by HubDub** [comment]
on this branch I am able to create a new payment type. looks good to me.

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by csmalley89 — COMMENTED** [review]
👍

**Comment by HubDub** [comment]
this worked for me. looks good.

**Review by JamsDuke — APPROVED** [review]
LGTM

**Pull request merged**
