### PR TITLE
Completed view

### PR DESCRIPTION
**Pull request by HubDub**
## Pull Request Description

Include the applicable information from the list below here 

Created the Order Completed view to thank customer for their order. this view does not receive any data from the database. 
## Steps to Test

examine code in PR and review for any typos, errors. Cannot test this until we can access the shopping cart view. 
## Link to Feature Ticket
#46

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
LGTM

**Review by JamsDuke — COMMENTED** [review]
Looks good!

**Review by csmalley89 — COMMENTED** [review]
👻 🎃 👍

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
