### PR TITLE
hid the customerId in the payment view

### PR DESCRIPTION
**Pull request by HubDub**
## Pull Request Description

this code hid the customerId in the payment view so user could not see it

## Steps to Test

Include the applicable information from the list below here

1. git fetch
2. checkout db-hideCustomerId branch
3. restart server
4. choose a customer with products in cart
5. go to cart
6. click add payment
7. customerId above name field should be hidden

## Link to Feature Ticket

#151

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
Code pulled, tested, and LGTM

**Review by Jgregnier — COMMENTED** [review]
🍊

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by delaineackerman — COMMENTED** [review]
lgtm

**Review by thrashMoneyVillainare — APPROVED** [review]
🇹🇭

**Pull request merged**
