### PR TITLE
Completed the SingleProductViewModel

### PR DESCRIPTION
**Pull request by thrashMoneyVillainare**
## Pull Request Description

Include the applicable information from the list below here 
1. This ViewModel is for giving data to the Single.cshtml view, allowing customers to see each product individually.
## Steps to Test
1. checkout to branch zr-SingleProductViewModel
2. open SingleProductViewModel form the ViewModels directory
3. check for syntax and/or spelling errors
4. review documentation for clarity 
## Link to Feature Ticket
#81

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
Double check that you're using System.Collections.Generic and Microsoft.AspNetCore.Mvc.Rendering
Other than those two looks good to me

**Comment by thrashMoneyVillainare** [comment]
Removed Microsoft.AspNetCore.Mvc.Rendering and System.Collections.Generic from the "using" statements as they are superfluous.

**Review by Jgregnier — COMMENTED** [review]
Grapes

**Review by JamsDuke — COMMENTED** [review]
Code looks good to merge!

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by csmalley89 — APPROVED** [review]
👍

**Pull request merged**
