### PR TITLE
Changed two customer controller connotations to customers in our code

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

Check that the customers drop down is now working properly.
Check that clicking create account or the current customer name takes you to customers/new form

### CODE REVIEW

**Review by thrashMoneyVillainare — COMMENTED** [review]
lgtm

**Comment by HubDub** [comment]
looks good

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by JamsDuke — COMMENTED** [review]
Pulled and tested, LGTM

**Review by delaineackerman — APPROVED** [review]
LGTM

**Pull request merged**
