### PR TITLE
aligned text vertically for individual product view

### PR DESCRIPTION
**Pull request by HubDub**
## Pull Request Description

this PR aligns the text in the individual view in a centered vertical alignment

## Steps to Test

Include the applicable information from the list below here

1. git fetch
2. git checkout db-formatSingleViewVertically
3. dotnet run
4. choose a product from the home page and make sure the resulting view has each property on a separate line, centered. 

## Link to Feature Ticket

#120

### CODE REVIEW

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by Jgregnier — COMMENTED** [review]
LGTM

**Review by thrashMoneyVillainare — COMMENTED** [review]
ltgm

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by JamsDuke — APPROVED** [review]
LGTM

**Pull request merged**
