### PR TITLE
Implemented Active Customer

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

Have Active Customer implemented and all ViewModels inheriting from BaseViewModel will have access to it. 
Created a AllProductsViewModel that returns all products to the view.
Created a Drop Down list in the top right to select the current active customer. 
## Steps to Test

Run the branch on your machine and see if it compiles.
## Link to Feature Ticket
#39, #79

### CODE REVIEW

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Comment by HubDub** [comment]
it compiled on my local machine. Good to go!

**Review by thrashMoneyVillainare — COMMENTED** [review]
grape!

**Review by csmalley89 — APPROVED** [review]
💩

**Review by JamsDuke — APPROVED** [review]
I have read through your code and everything looks good.

**Pull request merged**
