### PR TITLE
Adapted all methods in controllers to accept view models

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

Modified all of the methods in the controllers to pass a view model instead of just raw data.
Slightly modified two view models to resolve a few bugs happening on instantiation of the ViewModel.
## Steps to Test
1. Thoroughly comb the code for any misspelled or out of line code, a lot was changed.
2. Make sure the program runs and doesn't throw any odd errors.
## Link to Feature Ticket
#94, #95

### CODE REVIEW

**Comment by HubDub** [comment]
after pulling down the branch, I'm able to run this code successfully and navigate to the views that we have created thus far, new product, product types (both of these have no data but the nav bar comes up) and the single product view. Good to go.

**Review by JamsDuke — COMMENTED** [review]
Code pulled and functionality verified.  Looks good to merge!

**Comment by thrashMoneyVillainare** [comment]
This is working for me.

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by delaineackerman — APPROVED** [review]
LGTM

**Pull request merged**
