### PR TITLE
touched ViewModels dir and created BaseViewModel

### LINKED ISSUE #78: Base View Model
## Feature Description

This is the view model that all other view models will inherit from.
### Steps for Implementation

Contains a property that is a list of all customer IDs.
Contains a property of a "chosen customer" that has a getter and a setter.
If the getter returns a null customer then it returns the fake customer: "Create Account."
If the getter returns an active customer then it displays a firstName and lastName string.
Has a setter that sets the active customer.
Has a constructor function that takes in the context and returns all the select list items for the dropdown for each customer.
There are two private variables, see Steve's repo for reference.

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 
1. Touched ViewModels directory.
2. Touched BaseViewModel.cs
3. Implemented code from example repo for BaseViewModel.cs
## Steps to Test

Include the applicable information from the list below here
1. Verify that ViewModels folder exists.
2. Verify that BaseViewModel exists in the above mentioned folder.
3. Make sure code and naming conventions is consistent with the current project.
## Link to Feature Ticket

Provide the issue number that this pull request fixes
#78

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
👍

**Review by csmalley89 — APPROVED** [review]
LGTM

**Review by HubDub — COMMENTED** [review]
this looks good to me. names are consistent.

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by thrashMoneyVillainare — APPROVED** [review]
LGTM: Approved

**Pull request merged**
