### PR TITLE
Product views now have headings based on which type was clicked befor…

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 

1. Added dynamic headings to the category and sub category that a user is currently viewing.

## Steps to Test

Include the applicable information from the list below here

1. Switch to viewTitleFix branch.
1. Click on Product Types (Product Categories should be the heading above the product types)
1. Click any product type (heading should reflect the type you just clicked on above the sub types)
1. Click a sub-type (heading should reflect the sub-type you just clicked on above the product list)

## Link to Feature Ticket

Provide the issue number that this pull request fixes
Example: #136

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
Looks good to me

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by thrashMoneyVillainare — APPROVED** [review]
lgtu

**Comment by HubDub** [comment]
looks good

**Pull request merged**
